### ISSUE TITLE
New seismica cls file produces compilation errors

### ISSUE THREAD

**Issue by jbmuir** [WeAreSeismica/submission-template#13]
The most recent edition of the seismica class file seems to produce some errors in compilation; the first being
that the line
```
\addto\captionsenglish{\renewcommand{\abstractname}{}} % necessary to remove abstract title... don't know why
```
throws an error because ```\captionsenglish``` is from the ```babel``` package which is not imported. The other problem is that there is some problem with the``` \thanks``` command; it produces a runaway argument error then a too many } error (which should cancel, you would think!). I can't figure out what the underlying cause of this problem is though...

**Comment by thearagon** [comment]
Should be fixed now :)
