### ISSUE TITLE
Template CReDIT attributions are inconsistently capitalised

### ISSUE THREAD

**Issue by jbmuir** [WeAreSeismica/submission-template#8]
The CReDIT attributions within the template have inconsistent capitalisation; e.g. 
`\credit{Writing - original draft}{A. Firstauthor}` vs  `\credit{Writing - Review \& Editing}{people}`. This has (presumably) resulted in capitalisation issues in fully typeset final article versions. The standard for various CReDIT reference documents seems to be to not capitalise the second letter for single phrases (e.g. Project administration), but for the two writing attributions, to capitalise everything (e.g. Writing - Original Draft, Writing - Review & Editing).

**Comment by thearagon** [comment]
Good catch, thanks Jack! I will push an update in the next few days :)
