### ISSUE TITLE
AMSmath environments could be patched to automatically apply line numbers correctly

### ISSUE THREAD

**Issue by jbmuir** [WeAreSeismica/submission-template#9]
Currently, the default template requires uses to apply the linenomath environment around equations to number lines correctly, which is a hassle. This could be patched to be handled automatically; see e.g. https://tex.stackexchange.com/questions/461186/how-to-use-lineno-with-amsmath-align

**Comment by thearagon** [comment]
Will be patched in next update! Thanks a lot!
